export const mainBcg = "#0D0D0D"
export const secondaryBcg = "#1A1A1A"
export const mainFontColor = "#BFBFBF"
export const secondaryFontColor = "#6C6C6E"
export const tabBarItemColor = "#808080"
export const tarBarItemSelectedColor = "#fff"
export const componentBcg = "#1A1A1A"